(function () {
  'use strict';
  data["science"] = {
    title: 'ACT Science',
    desc: '40 questions · 40 minutes · Optional add-on · Data analysis & reasoning. Read graphs and tables carefully, trace experiment designs, and weigh competing viewpoints — nearly every answer comes straight from the passage.',
    categories: [
      {
        name: 'Data Representation',
        topics: [
          {name:'Reading Graphs & Charts', diff:'easy', visual:{type:'line',pts:[[0,10],[2,14],[4,18],[6,22]],fit:{m:2,b:10,dash:false},xMin:0,xMax:6,yMin:0,yMax:30,xLabel:'Week',yLabel:'Height (cm)',caption:'Rising trend: as weeks pass, plant height increases.'}, expl:`The most fundamental ACT Science skill. You'll see line graphs, bar charts, scatterplots, and pie charts. Questions on this topic rarely require memorized science facts — the answer is almost always sitting in the display if you read it correctly.<br><br>Before answering any question, spend 15 seconds orienting:<br>1. <strong>Read the axes labels</strong> — what's being measured?<br>2. <strong>Note the units</strong> — seconds? meters? percent?<br>3. <strong>Check the legend</strong> — what do different lines/bars/colors represent?<br>4. <strong>Spot the trend</strong> — increasing, decreasing, or no pattern?<br><br><strong>Types:</strong><br>• Line graphs: trends over time<br>• Bar charts: comparing categories<br>• Scatterplots: correlation between two variables<br>• Pie charts: parts of a whole<br><br>Most questions just require finding the right data point. Don't overthink — trace from the axis to the curve and back, and always confirm which series a question means.
<div class="example-box">
<strong>Question:</strong> A graph plots the growth of two plant species over 8 weeks. Week is on the x-axis and plant height (cm) is on the y-axis. The legend shows Species A as a solid line and Species B as a dashed line. At Week 5, Species A is at 30 cm and Species B is at 18 cm. What is the approximate height of Species B at Week 5?
<div class="step-box"><span class="step-num">1</span> Identify the right series: the question is about Species B, which is the <strong>dashed</strong> line.</div>
<div class="step-box"><span class="step-num">2</span> Locate Week 5 on the x-axis and find where the dashed line crosses it.</div>
<div class="step-box"><span class="step-num">3</span> Trace across to the y-axis and read the height.</div>
<strong>Answer:</strong> 18 cm. This is a straight lookup — the whole task is matching the legend to the correct line before you read anything. The pick of the wrong line changes the answer, so always confirm which series is being asked about.
</div><div class="warning-box">The most common trap is reading the wrong series or the wrong axis. Double-check the <strong>legend</strong> and the <strong>units on the y-axis</strong> — a graph in "millimeters" gives very different numbers than one in "centimeters." If a question names a variable, verify it matches an axis or legend entry before reading any value.</div>`},
          {name:'Reading Tables', diff:'easy', visual:{type:'bar',labels:['10°C','20°C','30°C','40°C'],values:[35,40,45,50],gold:false,caption:'Solubility of Salt X rises with temperature.'}, expl:`Tables present data in rows and columns. The key is knowing which row and column to look at. Table questions reward careful reading far more than science recall — the numbers you need are already on the page.<br><br>Strategy:<br>1. Read the column headers and row labels<br>2. Note any footnotes or conditions<br>3. For each question, identify exactly which cell(s) you need<br>4. Watch for patterns: as one variable increases, does another increase or decrease?<br><br>Many table questions are simple lookups. Others ask you to identify trends across multiple rows or columns. Take your time reading the table correctly — speed comes from accuracy, not rushing.
<div class="example-box">
<strong>Question:</strong> The table below shows the solubility of Salt X at different temperatures:<br>• 10°C → 35 g per 100 mL<br>• 20°C → 40 g per 100 mL<br>• 30°C → 45 g per 100 mL<br>According to the table, at what temperature does 40 g of Salt X dissolve in 100 mL of water?
<div class="step-box"><span class="step-num">1</span> Identify the target: you need the temperature where the amount is 40 g.</div>
<div class="step-box"><span class="step-num">2</span> Scan the second column for the value 40.</div>
<div class="step-box"><span class="step-num">3</span> Read across that row to the first column for the matching temperature.</div>
<strong>Answer:</strong> 20°C. Each cell belongs to one temperature, so the lookup is just finding the row that holds 40 g. Notice the pattern too: solubility rises by 5 g for every 10°C, which lets you predict cells the table may not show.
</div><div class="warning-box">Watch for footnotes and "conditions" text (like "measured at 1 atm"). A note tells you the results apply only under that condition, which the test uses to check whether you read the fine print. Also check the order of the rows and columns carefully before judging a trend — data that decreases in one column may increase in the next.</div>`},
          {name:'Interpolation & Extrapolation', diff:'medium', visual:{type:'line',pts:[[0,20],[2,26],[4,32],[6,38]],fit:{m:3,b:20,dash:true},xMin:0,xMax:10,yMin:0,yMax:55,xLabel:'Time (min)',yLabel:'Temp (°C)',caption:'Dashed fit line extends the trend beyond measured points.'}, expl:`<strong>Interpolation:</strong> Estimating a value BETWEEN known data points (for example, a value at a time between two measured times). It is usually reliable because you are filling a gap in an established trend.<br><br><strong>Extrapolation:</strong> Predicting a value BEYOND the given data (for example, past the last measured time). It is less certain because you extend a trend into a range the experiment never measured — the real relationship could bend.<br><br>Example: If a graph shows temperature rising 2° per minute from 20° at 0 min to 30° at 5 min, you can interpolate 26° at 3 min, or extrapolate 40° at 10 min — but only if the trend continues at a constant rate.
<div class="example-box">
<strong>Question:</strong> A beaker of water is heated and its temperature measured every 2 minutes:<br>• 0 min — 20°C<br>• 2 min — 26°C<br>• 4 min — 32°C<br>• 6 min — 38°C<br>If the trend continues at the same rate, what is the expected temperature at 5 minutes, and what is it at 10 minutes?
<div class="step-box"><span class="step-num">1</span> Find the rate: 26 − 20 = +6° every 2 min, so +3° per minute.</div>
<div class="step-box"><span class="step-num">2</span> Interpolate at 5 min: at 4 min it is 32°, so one minute later → 32 + 3 = 35°C.</div>
<div class="step-box"><span class="step-num">3</span> Extrapolate at 10 min: from 38° at 6 min, the gap is 4 minutes → 38 + (3 × 4) = 50°C.</div>
<strong>Answer:</strong> 35°C (between known points) and 50°C (beyond them). Interpolation follows the trend inside the data; extrapolation extends it, but the second answer holds only because the problem told you to assume the trend continues. On the ACT, that signal is usually "if the trend continues" — look for it before extending any line.
</div><div class="warning-box">Extrapolation answers are the easiest to get wrong. Only extrapolate when the question signals the trend continues — usually worded "if the trend continues." Do not confuse which value was interpolated vs. extrapolated when comparing answer ranges, and always confirm the units you are reading on the axis.</div>`},
          {name:'Identifying Trends & Patterns', diff:'medium', visual:{type:'line',pts:[[0,10],[1,20],[2,40],[3,80],[4,160]],fit:{m:0,b:0,dash:false},xMin:0,xMax:4,yMin:0,yMax:180,xLabel:'Hour',yLabel:'Colonies (thousands)',caption:'Counts double each hour — a direct, exponential trend.'}, expl:`Look for relationships between variables:<br><br>• <strong>Direct relationship:</strong> as one variable increases, the other increases<br>• <strong>Inverse relationship:</strong> as one increases, the other decreases<br>• <strong>No relationship:</strong> no clear pattern, the points scatter randomly<br>• <strong>Exponential:</strong> the curve gets steeper and steeper as values climb<br>• <strong>Plateau / logarithmic:</strong> the effect levels off after a certain point even as the input keeps rising<br><br>Pro tip: describe the trend in your own words before looking at answers — "as time increases, the population rises, then levels off." Then match your description against each choice so you are not tricked by a cleverly-worded answer that reverses the direction.
<div class="example-box">
<strong>Question:</strong> A student measures the number of bacterial colonies (in thousands) each hour:<br>• Hour 0 — 10<br>• Hour 1 — 20<br>• Hour 2 — 40<br>• Hour 3 — 80<br>• Hour 4 — 160<br>Describe the relationship between time and the number of colonies.
<div class="step-box"><span class="step-num">1</span> Check direction: as time increases, the colony count increases.</div>
<div class="step-box"><span class="step-num">2</span> Check shape: each hour the count doubles (×2), so the rate is not constant — it accelerates.</div>
<div class="step-box"><span class="step-num">3</span> Name the pattern: a <strong>direct, exponential</strong> relationship.</div>
<strong>Answer:</strong> Direct and exponential — the colony count rises over time, and it grows by a factor each hour rather than by a fixed amount. Answering "direct" alone is not enough; you must also capture the increasing steepness to match the question's trend vocabulary.
</div><div class="warning-box">The trap is describing only one variable (e.g., "the count doubled") while leaving time out. The question wants the TREND BETWEEN the variables. Also watch for plateaus: a trend that rises fast then flattens is its own pattern, not a steady slope — report it exactly.</div>`},
        ]
      },
      {
        name: 'Research Summaries',
        topics: [
          {name:'Experimental Design', diff:'medium', visual:{type:'bar',labels:['0 mg','100 mg','200 mg'],values:[32,26,22],gold:false,caption:'Higher caffeine dose → faster puzzle completion.'}, expl:`Every experiment has:<br><br>• <strong>Independent variable:</strong> what the scientist deliberately changes (the input, usually on the x-axis)<br>• <strong>Dependent variable:</strong> what is measured or observed — the result (usually the y-axis)<br>• <strong>Control variables:</strong> everything kept the same so the outcome can be blamed on the independent variable alone<br>• <strong>Control group:</strong> the baseline that receives no treatment or the standard treatment<br><br>Example: Testing if fertilizer helps plants grow. Independent = amount of fertilizer. Dependent = plant height. Controls = same water, light, soil. Control group = the plants with no fertilizer.<br><br>Most Research Summary questions hinge on this setup. Naming the variable that was deliberately changed and the variable that was measured is the single best time investment for these passages.
<div class="example-box">
<strong>Question:</strong> A scientist tests whether caffeine helps students concentrate. She gives 30 students either 0 mg, 100 mg, or 200 mg of caffeine, then times each one finishing a word-search puzzle. Identify the independent variable, the dependent variable, and the control group.
<div class="step-box"><span class="step-num">1</span> Independent variable: the amount of caffeine (0, 100, or 200 mg) — the scientist deliberately changes it.</div>
<div class="step-box"><span class="step-num">2</span> Dependent variable: the time to finish the puzzle — the measured result.</div>
<div class="step-box"><span class="step-num">3</span> Control group: the students who received <strong>0 mg</strong> of caffeine.</div>
<strong>Answer:</strong> Independent = caffeine dose; dependent = puzzle-finish time; control group = the 0 mg students. Once you see that the scientist changes caffeine and measures time, naming the pieces is the whole question.
</div><div class="warning-box">A frequent trap is treating the largest dose as the control group. Control is the <strong>no-treatment baseline</strong>, not the strongest treatment. The independent variable is what the researcher PLANS to change, not what happens to change on its own.</div>`},
          {name:'Comparing Experiments', diff:'medium', visual:{type:'bar',labels:['Grass','Tile'],values:[42,36],gold:false,caption:'Rolling distance on each surface at equal force.'}, expl:`Often you'll see Experiment 1, Experiment 2, Experiment 3 — similar setups that each differ in exactly one key way.<br><br>Ask yourself: what changed between experiments? That changed variable is what the later experiment is trying to test or hold constant.<br><br>Questions may ask:<br>• Why was Experiment 2 done? (typically to test a different variable or confirm results)<br>• How would the results change if a variable were modified?<br>• What conclusion is consistent with BOTH experiments?<br><br>Make a quick mental table — what was the same, what was different, and what was the result — so you compare deliberately rather than scanning the passage repeatedly.
<div class="example-box">
<strong>Question:</strong> Experiment 1 measures how far a ball rolls on grass when pushed with a 5 N force. Experiment 2 uses the same ball and force but rolls it on tile. Experiment 3 uses the same tile but doubles the force to 10 N. What is the main change between Experiment 1 and 2, and between 2 and 3?
<div class="step-box"><span class="step-num">1</span> Compare 1 and 2: force (5 N), ball, and size are the same — only the surface (grass → tile) changed.</div>
<div class="step-box"><span class="step-num">2</span> Compare 2 and 3: surface (tile) and ball are the same — only the force (5 N → 10 N) changed.</div>
<strong>Answer:</strong> Between 1 and 2 the change is the surface material; between 2 and 3 the change is the force. Because only one variable changes at a time, any difference in result can be attributed to that one variable.
</div><div class="warning-box">The trap is comparing Experiments 1 and 3 directly and claiming everything changed. When asked why one experiment was run, look only at the single variable separating it from the next. If two factors change at once, the experiment cannot say which caused an effect — the answer may be "cannot be determined."</div>`},
          {name:'Hypothesis Support', diff:'hard', visual:{type:'bar',labels:['Lake A','Lake B','Lake C'],values:[12,9,6],gold:false,caption:'Fewer species as pH drops — data support the hypothesis.'}, expl:`A hypothesis is a proposed explanation. The results either support it, contradict it, or leave it open. Key question types:<br><br>• Do the results support the hypothesis? → Yes if the data match what the hypothesis predicts, No if it contradicts<br>• Which hypothesis is supported by the data? → Compare each hypothesis against the results<br>• What would support the hypothesis? → Predict what the data WOULD look like if the hypothesis were true<br><br>Be objective. Don't let what sounds right override what the data actually shows. On the ACT the data comes straight from the passage and is treated as correct.
<div class="example-box">
<strong>Question:</strong> A student hypothesizes that as a lake's pH decreases (more acidic), the number of fish species in the lake decreases. She measures three lakes:<br>• Lake A — pH 7.2, 12 species<br>• Lake B — pH 6.5, 9 species<br>• Lake C — pH 5.8, 6 species<br>Do these results support the hypothesis?
<div class="step-box"><span class="step-num">1</span> Restate the prediction: lower pH → fewer species.</div>
<div class="step-box"><span class="step-num">2</span> Compare with the data: as pH falls from 7.2 to 5.8, the species count drops from 12 to 6.</div>
<strong>Answer:</strong> Yes — the results support the hypothesis because the data follow the predicted direction. Supporting means the data match the prediction, not that the explanation is proven true. To be unsupported, the data would need to contradict that direction.
</div><div class="warning-box">A subtle trap: data showing NO relationship does NOT support the hypothesis — it neither supports nor contradicts, and the ACT usually counts that as "not supported." Also do not claim a hypothesis is proven beyond these results; the questions ask only whether one experiment's data support it.</div>`},
        ]
      },
      {
        name: 'Conflicting Viewpoints',
        topics: [
          {name:'Understanding Multiple Hypotheses', diff:'hard', visual:{type:'bar',labels:['Impact','Climate'],values:[6,2],gold:false,caption:'Studies supporting each proposed cause.'}, expl:`This passage type presents 2-4 different explanations for the same phenomenon (e.g., why dinosaurs went extinct). Each explains the same basic facts but with a different cause and often a different time scale or mechanism.<br><br>Strategy:<br>1. Read the phenomenon description first — what is everyone explaining?<br>2. Read Scientist 1's view and note what they believe and WHY<br>3. Read Scientist 2's view: where do they AGREE with Scientist 1? Where do they DISAGREE?<br>4. Repeat for any additional viewpoints.<br><br>Make a quick T-chart on scratch paper: points of agreement vs. points of disagreement. These are the most time-consuming passages; many students save them for last.
<div class="example-box">
<strong>Question:</strong> Scientist A claims a sudden asteroid impact caused mass extinction about 66 million years ago, citing a layer of iridium in the rock. Scientist B claims the extinction was caused by gradual climate change over hundreds of thousands of years. What is the MAIN disagreement between the two?
<div class="step-box"><span class="step-num">1</span> Restate each view: A says sudden impact; B says gradual climate change.</div>
<div class="step-box"><span class="step-num">2</span> Note what they agree on: both accept that a mass extinction occurred.</div>
<div class="step-box"><span class="step-num">3</span> Identify the split: the <strong>cause</strong> and the <strong>speed</strong> of the extinction.</div>
<strong>Answer:</strong> They disagree on the cause and the timeline — A, an abrupt dramatic cause, and B, a gradual one. An answer saying they disagree on "whether the extinction happened" would be wrong, because both accept it.
</div><div class="warning-box">The trap is claiming the scientists disagree about everything, or calling a point agreement when neither has stated it. Only count a point as disagreement if one states it and the other states the opposite. If both are silent, they are not in conflict.</div>`},
          {name:'Identifying Agreement & Disagreement', diff:'medium', visual:{type:'bar',labels:['Scientist 1','Scientist 2'],values:[1,2],gold:false,caption:'Species count each scientist reports for the layer.'}, expl:`These questions ask explicitly whether Scientist 1 and Scientist 2 would agree or disagree on a given point.<br><br>For AGREEMENT: Both must say it (or clearly imply it). If one doesn't mention it, you cannot say they agree.<br>For DISAGREEMENT: One must say (or imply) yes and the other no. If both are silent on a topic, there is no demonstrated disagreement.<br><br>Stick strictly to what is stated. Do not infer beliefs beyond what each viewpoint actually says.
<div class="example-box">
<strong>Question:</strong> Scientist 1 says the layer contains a single species. Scientist 2 says the layer contains two species, one older than the other. Which would the two most likely with disagree on?<br>(A) The number of species in the layer (B) The color of the rock (C) Whether the layer is weathered (D) Whether the layer contains fossils at all.
<div class="step-box"><span class="step-num">1</span> Read each scientist: 1 says "a single species"; 2 says "two distinct species."</div>
<div class="step-box"><span class="step-num">2</span> The only concrete difference is NUMBER OF SPECIES — one says one, the other says two.</div>
<div class="step-box"><span class="step-num">3</span> Rule out (B) and (C) (neither discusses rock color or weathering) and (D) (both clearly consider fossils present).</div>
<strong>Answer:</strong> (A) — the number of species. The disagreement lies exactly where one says "one" and the other says "two." Do not invent a conflict where the two never overlap.
</div><div class="warning-box">A common trap is choosing a point where only ONE scientist expressed a view and inferring the other's objection. No stated conflict, no definite disagreement. Also reject an "agreement" answer unless both actually stated the point.</div>`},
          {name:'New Evidence Questions', diff:'hard', visual:{type:'bar',labels:['Slow','Rapid'],values:[1,5],gold:false,caption:'How well new evidence matches each scientist\'s claim.'}, expl:`Which viewpoint would be most weakened or strengthened by newly presented evidence?<br><br>Approach:<br>1. Understand what the new evidence actually shows<br>2. Check each viewpoint: does this evidence support or undermine their claim?<br>3. If the evidence contradicts what a viewpoint predicts → weakened<br>4. If the evidence matches what a viewpoint predicts → strengthened<br><br>You accept the new evidence as given and decide whose position it supports; do not try to judge the evidence itself.
<div class="example-box">
<strong>Question:</strong> Scientist 1 claims the rock formed slowly over millions of years. Scientist 2 claims it formed in a rapid event lasting less than 100 years. New evidence shows the rock solidified in under a century. Which scientist is strengthened, and which is weakened?
<div class="step-box"><span class="step-num">1</span> Summarize the evidence: solidification took <strong>much less than a century</strong> — very fast.</div>
<div class="step-box"><span class="step-num">2</span> Scientist 2's "fast/under a century" claim matches → <strong>strengthened</strong>.</div>
<div class="step-box"><span class="step-num">3</span> Scientist 1's "millions of years/very slow" claim is contradicted → <strong>weakened</strong>.</div>
<strong>Answer:</strong> Scientist 2 is strengthened; Scientist 1 is weakened. Match the new evidence's headline fact against what each position explicitly predicts about that fact.
</div><div class="warning-box">A trap is mis-reading the fact the evidence establishes (e.g., thinking "under a century" means slow) and swapping which scientist it helps. Read the evidence's headline fact first, then check each position's stated claim. "Weakened" needs the contradiction, not just a point the evidence never touches.</div>`},
        ]
      },
      {
        name: 'Background Knowledge — Biology',
        topics: [
          {name:'Cell Structure', diff:'easy', visual:{type:'bar',labels:['Nucleus','Mito','Ribosome','Membrane'],values:[5,4,2,3],gold:false,caption:'Relative size (µm) of common cell structures.'}, expl:`You may need basic biology knowledge on the ACT. Usually the passage sets the context, but comfortable knowledge helps you read faster and reason about which organelle does what when the passage traces effects on a cell.<br><br>• <strong>Nucleus:</strong> contains DNA, controls the cell<br>• <strong>Mitochondria:</strong> produce energy (ATP) through cellular respiration<br>• <strong>Ribosomes:</strong> make proteins<br>• <strong>Cell membrane:</strong> controls what enters and exits<br>• <strong>Chloroplasts:</strong> in plant cells only — photosynthesis<br><br><strong>Prokaryotic vs Eukaryotic:</strong> Prokaryotes (bacteria) lack a nucleus. Eukaryotes (plants, animals, fungi) have a nucleus and membrane-bound organelles.
<div class="example-box">
<strong>Question:</strong> A passage shows a plant cell and a bacterial cell. Which structure would you expect in the plant cell but NOT in the bacterial cell?
<div class="step-box"><span class="step-num">1</span> Recall the split: bacteria are prokaryotes; plants are eukaryotes.</div>
<div class="step-box"><span class="step-num">2</span> In plant cells, chloroplasts perform photosynthesis.</div>
<strong>Answer:</strong> Chloroplasts (and a membrane-bound nucleus). The bacterial cell still has ribosomes and a membrane, but it lacks chloroplasts and a true nucleus — so choices listing ribosomes or the cell membrane are wrong, being shared traits.
</div><div class="warning-box">A trap is assuming bacteria lack ribosomes (they do have them — they make proteins) or confusing mitochondria with chloroplasts. Mitochondria perform respiration in nearly all cells; chloroplasts are found only in plants and certain algae.</div>`},
          {name:'DNA, Genes & Proteins', diff:'medium', visual:{type:'line',pts:[[0,0],[2,5],[4,10],[6,10]],fit:{m:0,b:0,dash:false},xMin:0,xMax:6,yMin:0,yMax:15,xLabel:'Time (hr)',yLabel:'Protein amount (µg)',caption:'Protein production rises, then levels off.'}, expl:`Basic facts that help on the ACT:<br>• DNA is the genetic blueprint<br>• DNA → RNA → Protein (Central Dogma)<br>• Genes are segments of DNA that code for proteins<br>• Mutations are changes in the DNA sequence — harmful, neutral, or beneficial<br>• A mutation may change the amino acid sequence and therefore the protein's function<br>• <strong>Natural selection:</strong> organisms with advantageous traits survive and reproduce more<br><br>The ACT may not ask you to transcribe DNA to RNA cold, but passages often describe gene expression or mutation studies you interpret with this vocabulary.
<div class="example-box">
<strong>Question:</strong> A lab compares a normal hemoglobin gene with a mutated version and finds the mutated version produces a slightly different protein. The study also reports the mutation does NOT change the organism's ability to reproduce. What is the most likely effect of the mutation?
<div class="step-box"><span class="step-num">1</span> Apply central dogma: a gene (DNA) change can change the protein it codes for.</div>
<div class="step-box"><span class="step-num">2</span> The study says the protein differs — consistent with the DNA → protein link.</div>
<div class="step-box"><span class="step-num">3</span> Because reproduction is unchanged, the effect is most likely <strong>neutral</strong>.</div>
<strong>Answer:</strong> The mutation likely changes the protein but does not appreciably affect reproduction, so its effect is described as neutral. The concept pathways is central dogma plus the idea that a mutation's label comes from its impact on the organism's survival and reproduction.
</div><div class="warning-box">Do not assume every mutation is harmful — most are neutral, and the ACT supplies the effect. Also keep central dogma strictly DNA → RNA → protein. Getting the relationship backwards (protein → DNA) leads to the wrong choice.</div>`},
          {name:'Ecology & Ecosystems', diff:'easy', visual:{type:'line',pts:[[0,50],[5,80],[10,120],[15,80],[20,50]],fit:{m:0,b:0,dash:false},xMin:0,xMax:20,yMin:0,yMax:140,xLabel:'Year',yLabel:'Population',caption:'Prey and predator populations cycle with a time lag.'}, expl:`• <strong>Food chains:</strong> producers → primary consumers → secondary consumers → decomposers<br>• <strong>Predator-prey cycles:</strong> as prey increase, predators increase (with a lag), then prey decrease, predators decrease<br>• <strong>Carrying capacity:</strong> the maximum population an ecosystem can sustain<br>• <strong>Symbiosis:</strong> mutualism (both benefit), parasitism (one benefits, one harmed), commensalism (one benefits, the other unaffected)<br><br>A common graph: population vs. time showing cyclical predator-prey patterns, with the two lines rising and falling with a time lag.
<div class="example-box">
<strong>Question:</strong> A graph shows lynx (predator) and hare (prey) populations over 20 years. When the hare population peaks, the lynx population is still low; the lynx peak comes about a year later. Which statement best describes the relationship?
<div class="step-box"><span class="step-num">1</span> Recognize predators rise after prey rise and fall after prey fall — a lag.</div>
<div class="step-box"><span class="step-num">2</span> Name it: a predator-prey cycle with a time lag.</div>
<strong>Answer:</strong> The two populations show a cyclical predator-prey pattern, with lynx changes lagging behind hare changes by about a year. Predators grow after a good prey base appears, then their own numbers drive the prey down.
</div><div class="warning-box">The trap is claiming the predator rises at the same time as the prey. Look for the time lag — the predator curve trails the prey curve. Also keep "carrying capacity" separate from the short-term cycle swinging; carrying capacity is a rough ceiling, not the shape of each peak.</div>`},
        ]
      },
      {
        name: 'Background Knowledge — Chemistry',
        topics: [
          {name:'States of Matter', diff:'easy', visual:{type:'line',pts:[[0,-10],[4,0],[8,0],[12,100],[16,100],[20,120]],fit:{m:0,b:0,dash:false},xMin:0,xMax:20,yMin:-20,yMax:130,xLabel:'Time (min)',yLabel:'Temp (°C)',caption:'Heating curve of water — flat segments mark phase changes.'}, expl:`• <strong>Solid:</strong> fixed shape & volume, particles packed and vibrating in place<br>• <strong>Liquid:</strong> fixed volume, takes the container's shape<br>• <strong>Gas:</strong> no fixed shape or volume, particles spread far apart<br><br>Phase changes:<br>Melting (solid→liquid), Freezing (liquid→solid)<br>Vaporization / boiling (liquid→gas), Condensation (gas→liquid)<br>Sublimation (solid→gas, like dry ice)<br><br>Water freezes at 0°C and boils at 100°C — specific values worth memorizing.<br><br><strong>Energy:</strong> Melting and boiling require energy (endothermic). Freezing and condensing release energy (exothermic), so adding heat tends to move matter toward gas.
<div class="example-box">
<strong>Question:</strong> A sealed sample of water is cooled from 25°C to −10°C, crossing the freezing point. Describe the state change and whether energy is absorbed or released at the phase change.
<div class="step-box"><span class="step-num">1</span> Identify the change: the sample freezes (liquid → solid) at 0°C.</div>
<div class="step-box"><span class="step-num">2</span> Classify the energy: freezing is exothermic, so energy is released.</div>
<strong>Answer:</strong> The water freezes, changing from liquid to solid, and releases energy during the transition. The direction of the heating tells you the energy direction — freezing/condensing release, melting/boiling absorb.
</div><div class="warning-box">A trap is thinking melting "gives off" energy because it feels warm. Actually melting/boiling ABSORB energy while freezing/condensing RELEASE it — decide from the direction of the change. Note that during a phase change, the temperature stays constant even while energy flows, so flat segments on a graph signal a phase change.</div>`},
          {name:'pH Scale', diff:'easy', visual:{type:'ph',value:7,caption:'pH scale'}, expl:`<strong>pH 0–6:</strong> Acidic (more H⁺ ions) — lemon juice, stomach acid<br><strong>pH 7:</strong> Neutral — pure water<br><strong>pH 8–14:</strong> Basic/alkaline (more OH⁻ ions) — baking soda, bleach<br><br>Each pH unit is a 10× change in acidity. pH 3 is 10× more acidic than pH 4, and 100× more acidic than pH 5 — that multiplier matters in enzyme and water-quality passages.<br><br>The ACT may test this in a passage about enzyme activity or water quality.<br><br><strong>Buffers:</strong> resist pH changes by absorbing or releasing H⁺ ions, keeping pH stable.
<div class="example-box">
<strong>Question:</strong> A solution has pH 2 and a second solution has pH 6. How many times more acidic is the first solution than the second?
<div class="step-box"><span class="step-num">1</span> Find the difference: 6 − 2 = 4 pH units.</div>
<div class="step-box"><span class="step-num">2</span> Apply the 10× rule per unit: 10⁴ = 10,000.</div>
<strong>Answer:</strong> 10,000 times more acidic. Because lower pH means more H⁺ and each unit multiplies the H⁺ by 10, four units means a factor of 10 × 10 × 10 × 10. Lower pH = more acidic, so the pH-2 solution is the more acidic.
</div><div class="warning-box">The trap is adding the pH values (2 + 6 = 8) instead of subtracting their units (6 − 2 = 4), or treating the scale as straight-line equal steps rather than a 10× multiplier. Also be careful with direction: a lower pH number means MORE acidic.</div>`},
          {name:'Reaction Rates', diff:'medium', visual:{type:'line',pts:[[20,120],[40,60],[60,30]],fit:{m:-2.25,b:165,dash:false},xMin:20,xMax:60,yMin:0,yMax:140,xLabel:'Temp (°C)',yLabel:'Dissolve time (s)',caption:'Reactions speed up as temperature rises.'}, expl:`The rate of a reaction is how fast reactants convert to products. Reactions speed up when:<br>• <strong>Temperature increases</strong> (particles move faster, so more frequent and energetic collisions)<br>• <strong>Concentration increases</strong> (more particles to collide)<br>• <strong>Surface area increases</strong> (a solid broken smaller has more exposed surface)<br>• <strong>A catalyst is added</strong> (lowers the activation energy without being consumed)<br><br>Enzymes are biological catalysts — specific to their substrate (lock-and-key model).<br><br>These concepts appear frequently in Research Summary passages about chemistry and biology experiments.
<div class="example-box">
<strong>Question:</strong> A student measures how long (in seconds) a reactant powder takes to fully dissolve in water, then repeats with the same solid crushed into a fine dust, keeping everything else the same. Which factor changed, and how do you expect time to respond?
<div class="step-box"><span class="step-num">1</span> Identify the change: crushing gives the same solid a larger surface area.</div>
<div class="step-box"><span class="step-num">2</span> Connect to rate: more surface area → more contact with water → faster reaction.</div>
<div class="step-box"><span class="step-num">3</span> State the result: the dust dissolves faster, so the time decreases.</div>
<strong>Answer:</strong> Crushing increases surface area, speeding the reaction, so dissolving time decreases. You kept temperature and amount the same, so the only variable is surface — attribute the rate change to that single factor.
</div><div class="warning-box">A trap is treating temperature, concentration, or catalytic effects as if they were the same thing. A catalyst works by lowering activation energy WITHOUT being consumed and its presence changes reaction rate — separate each factor. When the test changes one thing at a time, blame the rate change on that exact factor.</div>`},
        ]
      },
      {
        name: 'Background Knowledge — Physics',
        topics: [
          {name:'Density & Buoyancy', diff:'easy', visual:{type:'bar',labels:['Wood','Ice','Water','Metal'],values:[0.6,0.9,1.0,2.5],gold:false,caption:'Density (g/cm³) — objects below 1.0 float, above 1.0 sink.'}, expl:`<strong>Density = Mass / Volume</strong><br><br>An object floats if its density is LESS than the fluid it sits in, and sinks if it is MORE. Water density = 1 g/cm³; objects with density < 1.0 float, > 1.0 sink.<br><br>That is why ice floats (density ≈ 0.9) and why a metal ship still floats — the craft's total volume is mostly air, keeping its average density below that of water. Density and buoyancy appear often in ACT science passages, so keep them as "density math that reads like data."
<div class="example-box">
<strong>Question:</strong> A block has mass 10 g and volume 5 cm³. Water density is 1 g/cm³. Will the block float or sink?
<div class="step-box"><span class="step-num">1</span> Compute density: density = mass ÷ volume.</div>
<div class="step-box"><span class="step-num">2</span> 10 g ÷ 5 cm³ = 2 g/cm³.</div>
<div class="step-box"><span class="step-num">3</span> Compare to water: 2 > 1, so it is denser.</div>
<strong>Answer:</strong> The block sinks because its density (2 g/cm³) is greater than water's (1 g/cm³). Density calculations are really 2-step problems ending in a "denser than the fluid = sink" compare.
</div><div class="warning-box">Careful with the subtlety: an object molded to trap air can float even if its material is denser than water, because its OVERALL (with-air) density drops below 1. Do the mass ÷ volume division correctly and check units — swapping mass and volume sends you the wrong way.</div>`},
          {name:'Energy', diff:'medium', visual:{type:'bar',labels:['KE (top)','PE (top)','KE (bottom)','PE (bottom)'],values:[0,100,100,0],gold:false,caption:'As a ball falls, PE converts to KE.'}, expl:`• <strong>Kinetic energy:</strong> energy of motion. KE = ½mv² (grows with mass and especially with speed — squared!)<br>• <strong>Potential energy:</strong> stored energy of position. Gravitational PE = mgh (mass × gravity × height)<br>• <strong>Conservation of energy:</strong> energy cannot be created or destroyed, only transformed (KE ↔ PE)<br><br>Example: a roller coaster at the top has max PE. As it drops, PE converts to KE; at the bottom KE is max and PE is min.<br><br>Heat flows from hot to cold. Specific heat is the energy required to raise 1 g of a substance by 1°C — water's high specific heat means it takes a lot of energy per degree.
<div class="example-box">
<strong>Question:</strong> A ball is dropped from a height onto a hard floor (ignoring air resistance). Just before it hits the floor, is its kinetic energy or potential energy greater?
<div class="step-box"><span class="step-num">1</span> Total energy is conserved (no air resistance): PE + KE stays constant.</div>
<div class="step-box"><span class="step-num">2</span> As it falls it loses height, so PE decreases while KE increases.</div>
<div class="step-box"><span class="step-num">3</span> Just before impact, most of the original PE has been transformed into KE.</div>
<strong>Answer:</strong> Its kinetic energy is greatest (nearly all kinetic, and PE near minimum) just before impact. Energy is transformed from PE to KE — nothing is destroyed, so answer choices saying energy is "lost" are wrong.
</div><div class="warning-box">A trap is treating the energy as "lost" at the bottom. Energy is conserved, just transformed. Also remember KE depends on speed squared, so doubling the speed quadruples the KE — a favorite "how many times" question.</div>`, },
          {name:'Forces & Motion', diff:'medium', visual:{type:'line',pts:[[0,0],[2,10],[4,20]],fit:{m:5,b:0,dash:false},xMin:0,xMax:4,yMin:0,yMax:25,xLabel:'Time (s)',yLabel:'Speed (m/s)',caption:'Constant acceleration: speed rises steadily.'}, expl:`<strong>Newton's Laws:</strong><br>1st: An object at rest stays at rest; an object in motion stays in motion unless a net outside force acts.<br>2nd: <code>F = ma</code> — force equals mass × acceleration.<br>3rd: Every action has an equal and opposite reaction.<br><br><strong>Gravity:</strong> pulls objects toward Earth at <code>g ≈ 9.8 m/s²</code>. All objects fall at the same rate, ignoring air resistance.<br><strong>Friction:</strong> opposes motion; static friction (at rest) is usually greater than kinetic friction (moving).<br><strong>Acceleration:</strong> rate of change of velocity, <code>a = Δv/Δt</code>.
<div class="example-box">
<strong>Question:</strong> A 20 N force is applied to a 4 kg object on a very low-friction track. What is its acceleration?
<div class="step-box"><span class="step-num">1</span> Use Newton's 2nd law: F = ma.</div>
<div class="step-box"><span class="step-num">2</span> Rearrange: a = F/m.</div>
<div class="step-box"><span class="step-num">3</span> Plug in: a = 20 N / 4 kg = 5 m/s².</div>
<strong>Answer:</strong> 5 m/s². Newton's second law: the same force on a larger mass gives less acceleration — exactly the F = ma relationship a passage's force/mass/acceleration table sets you up to apply.
</div><div class="warning-box">A trap is cancelling the pair in Newton's 3rd law (the force of gravity accelerating vs. where a force pair acts on different objects, so they do not cancel in F = ma on one body). Do not forget the acceleration units (m/s²) or that all objects fall at the same rate where air is ignored.</div>`},
        ]
      },
      {
        name: 'Background Knowledge — Earth & Space',
        topics: [
          {name:'Plate Tectonics', diff:'easy', visual:{type:'bar',labels:['Convergent','Divergent','Transform'],values:[3,2,1],gold:false,caption:'Distinct geological features at each boundary type.'}, expl:`Earth's crust is divided into plates that move slowly over geological time.<br><br>
• <strong>Convergent boundaries:</strong> plates collide → mountains, volcanoes, trenches<br>
• <strong>Divergent boundaries:</strong> plates separate → new crust forms, mid-ocean ridges<br>
• <strong>Transform boundaries:</strong> plates slide past each other → earthquakes<br><br>
Matching fossils found on different continents support continental drift. This is a classic ACT Conflicting Viewpoints topic — the passage may present different theories about what drives plate motion.
<div class="example-box">
<strong>Question:</strong> A student studies two plates at a mid-ocean ridge and observes that new rock forms continuously at the ridge while the plates move apart. Which boundary type is this, and where is the youngest rock located?
<div class="step-box"><span class="step-num">1</span> At a divergent boundary the plates move APART.</div>
<div class="step-box"><span class="step-num">2</span> New rock that forms at the gap comes from upwelling of spreading molten material.</div>
<div class="step-box"><span class="step-num">3</span> The fresh rock at the ridge is the newest, getting older with distance from the ridge.</div>
<strong>Answer:</strong> This is a divergent boundary, and the youngest rock forms at the ridge crest (oldest farther away). Questions often compare the width of the bands of new rock to the rate of spreading.
</div><div class="warning-box">Do not read the boundary the wrong way from its land form. Mountains and volcanoes are typically at a convergent boundary, trenches point to collision too, while mid-ocean ridges and new crust are divergent. Match each boundary to the right landform, and assign the "newest rock" to the ridge.</div>`},
          {name:'Greenhouse Effect', diff:'medium', visual:{type:'line',pts:[[1900,300],[1940,310],[1980,335],[2000,370],[2020,415]],fit:{m:0,b:0,dash:false},xMin:1900,xMax:2020,yMin:250,yMax:450,xLabel:'Year',yLabel:'CO₂ (ppm)',caption:'Atmospheric CO₂ rises over the past century.'}, expl:`Greenhouse gases (CO₂, methane, water vapor) trap heat in Earth's atmosphere.<br><br>
• Sun's shortwave sunlight passes through the atmosphere and warms the surface<br>
• The surface re-radiates heat as infrared (longwave) radiation<br>
• Greenhouse gases absorb the infrared, keeping the planet warm<br>
• More greenhouse gases → more heat trapped → rising global temperatures<br><br>
This appears in Data Representation passages (graphed CO₂ vs. temperature over time) and in Conflicting Viewpoints passages.
<div class="example-box">
<strong>Question:</strong> A graph shows 100 years of data with two rising lines: average global temperature and atmospheric CO₂, with the CO₂ line ahead of the temperature line. Which statement best matches the graph?
<div class="step-box"><span class="step-num">1</span> Read both curves: both generally increase over the same time span.</div>
<div class="step-box"><span class="step-num">2</span> Note the ordering: the CO₂ line rises roughly with (just before) the temperature.</div>
<strong>Answer:</strong> The two curves show a general trend in the same direction — as CO₂ increases, temperature also rises. The question usually asks only to report the correlation shown in the graph, not to assert the mechanism beyond it.
</div><div class="warning-box">The trap is over-asserting. If the problem supplies only correlation, describe the trend ("the two tend to rise together") rather than a strong causal claim. Read the y-axis of the line you accept as the answer, and don't reverse the direction of the relationship in your wording.</div>`},
          {name:'The Solar System', diff:'easy', visual:{type:'bar',labels:['Mercury','Venus','Earth','Mars','Jupiter'],values:[0.4,0.7,1.0,1.5,5.2],gold:false,caption:'Distance from the Sun (AU)'}, expl:`• Planets orbit the Sun in elliptical (nearly circular) paths<br>• Inner planets (Mercury, Venus, Earth, Mars): rocky, small<br>• Outer planets (Jupiter, Saturn, Uranus, Neptune): gas giants, large<br>• <strong>Gravity keeps planets in orbit — stronger when the planet is closer to the Sun</strong><br>• The Moon orbits Earth; its gravity causes tides<br><br>ACT passages may describe discoveries about exoplanets or compare planetary atmospheres. The science is explained in the passage — read carefully rather than rely purely on memory.
<div class="example-box">
<strong>Question:</strong> The passage ranks three planets by how strongly they are pulled toward the Sun: Mercury (close), Earth (middle), Neptune (far). Which factor determines gravitational pull between a planet and the Sun?
<div class="step-box"><span class="step-num">1</span> Recall that gravity between two objects depends strongly on distance.</div>
<div class="step-box"><span class="step-num">2</span> The closer the planet, the stronger the pull toward the Sun.</div>
<div class="step-box"><span class="step-num">3</span> So the pull ranks Mercury (strongest) > Earth > Neptune (weakest).</div>
<strong>Answer:</strong> Distance from the Sun — gravity is stronger the closer the planet is, making Mercury the most strongly pulled of the three. The relationship is stated in the passage; you just match distance ordering to the pull ordering.
</div><div class="warning-box">A trap is guessing by mass alone. The gravitational pull toward the Sun grows as distance shrinks, so order the planets by distance from the Sun rather than by their rocky/gas-giant type. Use the passage's stated relationship instead of importing extra facts.</div>`},
        ]
      },
    ]
  };
})();