(function () {
  'use strict';
  data["science"] = {
    title: 'ACT Science',
    desc: '40 questions · 35 minutes · Optional add-on · Data analysis & reasoning. Read graphs and tables carefully, trace experiment designs, and weigh competing viewpoints — nearly every answer comes straight from the passage.',
    categories: [
      {
        name: 'Data Representation',
        topics: [
          {name:'Reading Graphs & Charts', diff:'easy', visual:{type:'line',pts:[[0,10],[2,14],[4,18],[6,22]],fit:{m:2,b:10,dash:false},xMin:0,xMax:6,yMin:0,yMax:30,xLabel:'Week',yLabel:'Height (cm)',caption:'Rising trend: as weeks pass, plant height increases.'}, expl:`The most fundamental ACT Science skill. You'll see line graphs, bar charts, scatterplots, and pie charts. Questions on this topic rarely require memorized science facts — the answer is almost always sitting in the display if you read it correctly.<br><br>Before answering any question, spend 15 seconds orienting:<br>1. <strong>Read the axes labels</strong> — what's being measured?<br>2. <strong>Note the units</strong> — seconds? meters? percent?<br>3. <strong>Check the legend</strong> — what do different lines/bars/colors represent?<br>4. <strong>Spot the trend</strong> — increasing, decreasing, or no pattern?<br><br><strong>Types:</strong><br>• Line graphs: trends over time<br>• Bar charts: comparing categories<br>• Scatterplots: correlation between two variables<br>• Pie charts: parts of a whole<br><br>Most questions just require finding the right data point. Don't overthink — trace from the axis to the curve and back, and always confirm which series a question means.
<div class="example-box">
<strong>Question:</strong> A graph plots the growth of two plant species over 8 weeks. Week is on the x-axis and plant height (cm) is on the y-axis. The legend shows Species A as a solid line and Species B as a dashed line. At Week 5, Species A is at 30 cm and Species B is at 18 cm. What is the approximate height of Species B at Week 5?
<div class="step-box"><span class="step-num">1</span> Identify the right series: the question is about Species B, which is the <strong>dashed</strong> line.</div>
<div class="step-box"><span class="step-num">2</span> Locate Week 5 on the x-axis and find where the dashed line crosses it.</div>
<div class="step-box"><span class="step-num">3</span> Trace across to the y-axis and read the height.</div>
<strong>Answer:</strong> 18 cm. This is a straight lookup — the whole task is matching the legend to the correct line before you read anything. The pick of the wrong line changes the answer, so always confirm which series is being asked about.
</div><div class="warning-box">The most common trap is reading the wrong series or the wrong axis. Double-check the <strong>legend</strong> and the <strong>units on the y-axis</strong> — a graph in "millimeters" gives very different numbers than one in "centimeters." If a question names a variable, verify it matches an axis or legend entry before reading any value.</div>`},
          {name:'Reading Tables', diff:'easy', visual:{type:'bar',labels:['10°C','20°C','30°C','40°C'],values:[35,40,45,50],gold:false,caption:'Solubility of Salt X rises with temperature.'}, expl:`Tables present data in rows and columns. The key is knowing which row and column to look at. Table questions reward careful reading far more than science recall — the numbers you need are already on the page.<br><br>Strategy:<br>1. Read the column headers and row labels<br>2. Note any footnotes or conditions<br>3. For each question, identify exactly which cell(s) you need<br>4. Watch for patterns: as one variable increases, does another increase or decrease?<br><br>Many table questions are simple lookups. Others ask you to identify trends across multiple rows or columns. Take your time reading the table correctly — speed comes from accuracy, not rushing.
<div class="example-box">
<strong>Question:</strong> The table below shows the solubility of Salt X at different temperatures:<br>• 10°C → 35 g per 100 mL<br>• 20°C → 40 g per 100 mL<br>• 30°C → 45 g per 100 mL<br>According to the table, at what temperature does 40 g of Salt X dissolve in 100 mL of water?
<div class="step-box"><span class="step-num">1</span> Identify the target: you need the temperature where the amount is 40 g.</div>
<div class="step-box"><span class="step-num">2</span> Scan the second column for the value 40.</div>
<div class="step-box"><span class="step-num">3</span> Read across that row to the first column for the matching temperature.</div>
<strong>Answer:</strong> 20°C. Each cell belongs to one temperature, so the lookup is just finding the row that holds 40 g. Notice the pattern too: solubility rises by 5 g for every 10°C, which lets you predict cells the table may not show.
</div><div class="warning-box">Watch for footnotes and "conditions" text (like "measured at 1 atm"). A note tells you the results apply only under that condition, which the test uses to check whether you read the fine print. Also check the order of the rows and columns carefully before judging a trend — data that decreases in one column may increase in the next.</div>`},
          {name:'Interpolation & Extrapolation', diff:'medium', visual:{type:'line',pts:[[0,20],[2,26],[4,32],[6,38]],fit:{m:3,b:20,dash:true},xMin:0,xMax:10,yMin:0,yMax:55,xLabel:'Time (min)',yLabel:'Temp (°C)',caption:'Dashed fit line extends the trend beyond measured points.'}, expl:`<strong>Interpolation:</strong> Estimating a value BETWEEN known data points (for example, a value at a time between two measured times). It is usually reliable because you are filling a gap in an established trend.<br><br><strong>Extrapolation:</strong> Predicting a value BEYOND the given data (for example, past the last measured time). It is less certain because you extend a trend into a range the experiment never measured — the real relationship could bend.<br><br>Example: If a graph shows temperature rising 2° per minute from 20° at 0 min to 30° at 5 min, you can interpolate 26° at 3 min, or extrapolate 40° at 10 min — but only if the trend continues at a constant rate.
<div class="example-box">
<strong>Question:</strong> A beaker of water is heated and its temperature measured every 2 minutes:<br>• 0 min — 20°C<br>• 2 min — 26°C<br>• 4 min — 32°C<br>• 6 min — 38°C<br>If the trend continues at the same rate, what is the expected temperature at 5 minutes, and what is it at 10 minutes?
<div class="step-box"><span class="step-num">1</span> Find the rate: 26 − 20 = +6° every 2 min, so +3° per minute.</div>
<div class="step-box"><span class="step-num">2</span> Interpolate at 5 min: at 4 min it is 32°, so one minute later → 32 + 3 = 35°C.</div>
<div class="step-box"><span class="step-num">3</span> Extrapolate at 10 min: from 38° at 6 min, the gap is 4 minutes → 38 + (3 × 4) = 50°C.</div>
<strong>Answer:</strong> 35°C (between known points) and 50°C (beyond them). Interpolation follows the trend inside the data; extrapolation extends it, but the second answer holds only because the problem told you to assume the trend continues. On the ACT, that signal is usually "if the trend continues" — look for it before extending any line.
</div><div class="warning-box">Extrapolation answers are the easiest to get wrong. Only extrapolate when the question signals the trend continues — usually worded "if the trend continues." Do not confuse which value was interpolated vs. extrapolated when comparing answer ranges, and always confirm the units you are reading on the axis.</div>`},
          {name:'Identifying Trends & Patterns', diff:'medium', visual:{type:'line',pts:[[0,10],[1,20],[2,40],[3,80],[4,160]],fit:{m:0,b:0,dash:false},xMin:0,xMax:4,yMin:0,yMax:180,xLabel:'Hour',yLabel:'Colonies (thousands)',caption:'Counts double each hour — a direct, exponential trend.'}, expl:`Look for relationships between variables:<br><br>• <strong>Direct relationship:</strong> as one variable increases, the other increases<br>• <strong>Inverse relationship:</strong> as one increases, the other decreases<br>• <strong>No relationship:</strong> no clear pattern, the points scatter randomly<br>• <strong>Exponential:</strong> the curve gets steeper and steeper as values climb<br>• <strong>Plateau / logarithmic:</strong> the effect levels off after a certain point even as the input keeps rising<br><br>Pro tip: describe the trend in your own words before looking at answers — "as time increases, the population rises, then levels off." Then match your description against each choice so you are not tricked by a cleverly-worded answer that reverses the direction.
<div class="example-box">
<strong>Question:</strong> A student measures the number of bacterial colonies (in thousands) each hour:<br>• Hour 0 — 10<br>• Hour 1 — 20<br>• Hour 2 — 40<br>• Hour 3 — 80<br>• Hour 4 — 160<br>Describe the relationship between time and the number of colonies.
<div class="step-box"><span class="step-num">1</span> Check direction: as time increases, the colony count increases.</div>
<div class="step-box"><span class="step-num">2</span> Check shape: each hour the count doubles (×2), so the rate is not constant — it accelerates.</div>
<div class="step-box"><span class="step-num">3</span> Name the pattern: a <strong>direct, exponential</strong> relationship.</div>
<strong>Answer:</strong> Direct and exponential — the colony count rises over time, and it grows by a factor each hour rather than by a fixed amount. Answering "direct" alone is not enough; you must also capture the increasing steepness to match the question's trend vocabulary.
</div><div class="warning-box">The trap is describing only one variable (e.g., "the count doubled") while leaving time out. The question wants the TREND BETWEEN the variables. Also watch for plateaus: a trend that rises fast then flattens is its own pattern, not a steady slope — report it exactly.</div>`},
        ]
      },
      {
        name: 'Research Summaries',
        topics: [
          {name:'Experimental Design', diff:'medium', visual:{type:'bar',labels:['0 mg','100 mg','200 mg'],values:[32,26,22],gold:false,caption:'Higher caffeine dose → faster puzzle completion.'}, expl:`Every experiment has:<br><br>• <strong>Independent variable:</strong> what the scientist deliberately changes (the input, usually on the x-axis)<br>• <strong>Dependent variable:</strong> what is measured or observed — the result (usually the y-axis)<br>• <strong>Control variables:</strong> everything kept the same so the outcome can be blamed on the independent variable alone<br>• <strong>Control group:</strong> the baseline that receives no treatment or the standard treatment<br><br>Example: Testing if fertilizer helps plants grow. Independent = amount of fertilizer. Dependent = plant height. Controls = same water, light, soil. Control group = the plants with no fertilizer.<br><br>Most Research Summary questions hinge on this setup. Naming the variable that was deliberately changed and the variable that was measured is the single best time investment for these passages.
<div class="example-box">
<strong>Question:</strong> A scientist tests whether caffeine helps students concentrate. She gives 30 students either 0 mg, 100 mg, or 200 mg of caffeine, then times each one finishing a word-search puzzle. Identify the independent variable, the dependent variable, and the control group.
<div class="step-box"><span class="step-num">1</span> Independent variable: the amount of caffeine (0, 100, or 200 mg) — the scientist deliberately changes it.</div>
<div class="step-box"><span class="step-num">2</span> Dependent variable: the time to finish the puzzle — the measured result.</div>
<div class="step-box"><span class="step-num">3</span> Control group: the students who received <strong>0 mg</strong> of caffeine.</div>
<strong>Answer:</strong> Independent = caffeine dose; dependent = puzzle-finish time; control group = the 0 mg students. Once you see that the scientist changes caffeine and measures time, naming the pieces is the whole question.
</div><div class="warning-box">A frequent trap is treating the largest dose as the control group. Control is the <strong>no-treatment baseline</strong>, not the strongest treatment. The independent variable is what the researcher PLANS to change, not what happens to change on its own.</div>`},
          {name:'Comparing Experiments', diff:'medium', visual:{type:'bar',labels:['Grass','Tile'],values:[42,36],gold:false,caption:'Rolling distance on each surface at equal force.'}, expl:`Often you'll see Experiment 1, Experiment 2, Experiment 3 — similar setups that each differ in exactly one key way.<br><br>Ask yourself: what changed between experiments? That changed variable is what the later experiment is trying to test or hold constant.<br><br>Questions may ask:<br>• Why was Experiment 2 done? (typically to test a different variable or confirm results)<br>• How would the results change if a variable were modified?<br>• What conclusion is consistent with BOTH experiments?<br><br>Make a quick mental table — what was the same, what was different, and what was the result — so you compare deliberately rather than scanning the passage repeatedly.
<div class="example-box">
<strong>Question:</strong> Experiment 1 measures how far a ball rolls on grass when pushed with a 5 N force. Experiment 2 uses the same ball and force but rolls it on tile. Experiment 3 uses the same tile but doubles the force to 10 N. What is the main change between Experiment 1 and 2, and between 2 and 3?
<div class="step-box"><span class="step-num">1</span> Compare 1 and 2: force (5 N), ball, and size are the same — only the surface (grass → tile) changed.</div>
<div class="step-box"><span class="step-num">2</span> Compare 2 and 3: surface (tile) and ball are the same — only the force (5 N → 10 N) changed.</div>
<strong>Answer:</strong> Between 1 and 2 the change is the surface material; between 2 and 3 the change is the force. Because only one variable changes at a time, any difference in result can be attributed to that one variable.
</div><div class="warning-box">The trap is comparing Experiments 1 and 3 directly and claiming everything changed. When asked why one experiment was run, look only at the single variable separating it from the next. If two factors change at once, the experiment cannot say which caused an effect — the answer may be "cannot be determined."</div>`},
          {name:'Hypothesis Support', diff:'hard', visual:{type:'bar',labels:['Lake A','Lake B','Lake C'],values:[12,9,6],gold:false,caption:'Fewer species as pH drops — data support the hypothesis.'}, expl:`A hypothesis is a proposed explanation. The results either support it, contradict it, or leave it open. Key question types:<br><br>• Do the results support the hypothesis? → Yes if the data match what the hypothesis predicts, No if it contradicts<br>• Which hypothesis is supported by the data? → Compare each hypothesis against the results<br>• What would support the hypothesis? → Predict what the data WOULD look like if the hypothesis were true<br><br>Be objective. Don't let what sounds right override what the data actually shows. On the ACT the data comes straight from the passage and is treated as correct.
<div class="example-box">
<strong>Question:</strong> A student hypothesizes that as a lake's pH decreases (more acidic), the number of fish species in the lake decreases. She measures three lakes:<br>• Lake A — pH 7.2, 12 species<br>• Lake B — pH 6.5, 9 species<br>• Lake C — pH 5.8, 6 species<br>Do these results support the hypothesis?
<div class="step-box"><span class="step-num">1</span> Restate the prediction: lower pH → fewer species.</div>
<div class="step-box"><span class="step-num">2</span> Compare with the data: as pH falls from 7.2 to 5.8, the species count drops from 12 to 6.</div>
<strong>Answer:</strong> Yes — the results support the hypothesis because the data follow the predicted direction. Supporting means the data match the prediction, not that the explanation is proven true. To be unsupported, the data would need to contradict that direction.
</div><div class="warning-box">A subtle trap: data showing NO relationship does NOT support the hypothesis — it neither supports nor contradicts, and the ACT usually counts that as "not supported." Also do not claim a hypothesis is proven beyond these results; the questions ask only whether one experiment's data support it.</div>`},
        ]
      },
      {
        name: 'Conflicting Viewpoints',
        topics: [
          {name:'Understanding Multiple Hypotheses', diff:'hard', visual:{type:'bar',labels:['Impact','Climate'],values:[6,2],gold:false,caption:'Studies supporting each proposed cause.'}, expl:`This passage type presents 2-4 different explanations for the same phenomenon (e.g., why dinosaurs went extinct). Each explains the same basic facts but with a different cause and often a different time scale or mechanism.<br><br>Strategy:<br>1. Read the phenomenon description first — what is everyone explaining?<br>2. Read Scientist 1's view and note what they believe and WHY<br>3. Read Scientist 2's view: where do they AGREE with Scientist 1? Where do they DISAGREE?<br>4. Repeat for any additional viewpoints.<br><br>Make a quick T-chart on scratch paper: points of agreement vs. points of disagreement. These are the most time-consuming passages; many students save them for last.
<div class="example-box">
<strong>Question:</strong> Scientist A claims a sudden asteroid impact caused mass extinction about 66 million years ago, citing a layer of iridium in the rock. Scientist B claims the extinction was caused by gradual climate change over hundreds of thousands of years. What is the MAIN disagreement between the two?
<div class="step-box"><span class="step-num">1</span> Restate each view: A says sudden impact; B says gradual climate change.</div>
<div class="step-box"><span class="step-num">2</span> Note what they agree on: both accept that a mass extinction occurred.</div>
<div class="step-box"><span class="step-num">3</span> Identify the split: the <strong>cause</strong> and the <strong>speed</strong> of the extinction.</div>
<strong>Answer:</strong> They disagree on the cause and the timeline — A, an abrupt dramatic cause, and B, a gradual one. An answer saying they disagree on "whether the extinction happened" would be wrong, because both accept it.
</div><div class="warning-box">The trap is claiming the scientists disagree about everything, or calling a point agreement when neither has stated it. Only count a point as disagreement if one states it and the other states the opposite. If both are silent, they are not in conflict.</div>`},
          {name:'Identifying Agreement & Disagreement', diff:'medium', visual:{type:'bar',labels:['Scientist 1','Scientist 2'],values:[1,2],gold:false,caption:'Species count each scientist reports for the layer.'}, expl:`These questions ask explicitly whether Scientist 1 and Scientist 2 would agree or disagree on a given point.<br><br>For AGREEMENT: Both must say it (or clearly imply it). If one doesn't mention it, you cannot say they agree.<br>For DISAGREEMENT: One must say (or imply) yes and the other no. If both are silent on a topic, there is no demonstrated disagreement.<br><br>Stick strictly to what is stated. Do not infer beliefs beyond what each viewpoint actually says.
<div class="example-box">
<strong>Question:</strong> Scientist 1 says the layer contains a single species. Scientist 2 says the layer contains two species, one older than the other. Which would the two most likely with disagree on?<br>(A) The number of species in the layer (B) The color of the rock (C) Whether the layer is weathered (D) Whether the layer contains fossils at all.
<div class="step-box"><span class="step-num">1</span> Read each scientist: 1 says "a single species"; 2 says "two distinct species."</div>
<div class="step-box"><span class="step-num">2</span> The only concrete difference is NUMBER OF SPECIES — one says one, the other says two.</div>
<div class="step-box"><span class="step-num">3</span> Rule out (B) and (C) (neither discusses rock color or weathering) and (D) (both clearly consider fossils present).</div>
<strong>Answer:</strong> (A) — the number of species. The disagreement lies exactly where one says "one" and the other says "two." Do not invent a conflict where the two never overlap.
</div><div class="warning-box">A common trap is choosing a point where only ONE scientist expressed a view and inferring the other's objection. No stated conflict, no definite disagreement. Also reject an "agreement" answer unless both actually stated the point.</div>`},
          {name:'New Evidence Questions', diff:'hard', visual:{type:'bar',labels:['Slow','Rapid'],values:[1,5],gold:false,caption:'How well new evidence matches each scientist\'s claim.'}, expl:`Which viewpoint would be most weakened or strengthened by newly presented evidence?<br><br>Approach:<br>1. Understand what the new evidence actually shows<br>2. Check each viewpoint: does this evidence support or undermine their claim?<br>3. If the evidence contradicts what a viewpoint predicts → weakened<br>4. If the evidence matches what a viewpoint predicts → strengthened<br><br>You accept the new evidence as given and decide whose position it supports; do not try to judge the evidence itself.
<div class="example-box">
<strong>Question:</strong> Scientist 1 claims the rock formed slowly over millions of years. Scientist 2 claims it formed in a rapid event lasting less than 100 years. New evidence shows the rock solidified in under a century. Which scientist is strengthened, and which is weakened?
<div class="step-box"><span class="step-num">1</span> Summarize the evidence: solidification took <strong>much less than a century</strong> — very fast.</div>
<div class="step-box"><span class="step-num">2</span> Scientist 2's "fast/under a century" claim matches → <strong>strengthened</strong>.</div>
<div class="step-box"><span class="step-num">3</span> Scientist 1's "millions of years/very slow" claim is contradicted → <strong>weakened</strong>.</div>
<strong>Answer:</strong> Scientist 2 is strengthened; Scientist 1 is weakened. Match the new evidence's headline fact against what each position explicitly predicts about that fact.
</div><div class="warning-box">A trap is mis-reading the fact the evidence establishes (e.g., thinking "under a century" means slow) and swapping which scientist it helps. Read the evidence's headline fact first, then check each position's stated claim. "Weakened" needs the contradiction, not just a point the evidence never touches.</div>`},
        ]
      },
      {
        name: 'Scientific Investigation',
        desc: '18–32%',
        topics: [
          {name:'Experimental Design', diff:'medium', visual:{type:'bar',labels:['Controlled','Uncontrolled'],values:[5,2],gold:false,caption:'Controlled experiment isolates one variable.'}, expl:`ACT Science passages often ask you to evaluate how well an experiment was designed. A strong experiment changes only one independent variable, holds all controls constant, and measures one clear dependent variable. When comparing studies, ask what changed between them and whether the groups are comparable.<br><br><strong>Key questions:</strong><br>• Was only one variable changed between groups?<br>• Were all other conditions kept the same?<br>• Is there a clear baseline or control group?<br>• Could another factor explain the difference?<br><br>Spotting weak design is half the battle — if the test asks why an experiment was repeated or why a control group exists, the answer is always about isolating one factor.`},
          {name:'Variables & Controls', diff:'easy', visual:{type:'bar',labels:['Independent','Dependent','Controlled'],values:[1,1,3],gold:false,caption:'Every good experiment has one independent and one dependent variable.'}, expl:`The three variable types that appear in almost every ACT Science Research Summary.<br><br>• <strong>Independent variable:</strong> what the scientist deliberately changes<br>• <strong>Dependent variable:</strong> what is measured as a result<br>• <strong>Control variables:</strong> everything kept the same so the result can be attributed to the independent variable alone<br><br><strong>Control group:</strong> the baseline that receives no treatment or a standard treatment — without it, you cannot say whether the treatment did anything.<br><br>If a question asks what was changed between two experiments, look for the one thing that differs; everything else is held constant on purpose.`},
          {name:'Interpreting Methods', diff:'medium', visual:{type:'line',pts:[[0,20],[2,25],[4,30],[6,35]],fit:{m:2.5,b:20,dash:true},xMin:0,xMax:6,yMin:15,yMax:40,xLabel:'Step',yLabel:'Result',caption:'A clear procedure produces a clean trend you can follow step-by-step.'}, expl:`Science passages describe a procedure — a sequence of steps the researcher actually performed. Your job is to read that procedure and determine what each step was meant to measure or control.<br><br><strong>Reading strategy:</strong><br>1. Identify the goal of the passage before reading the details.<br>2. For each experimental group, list what was changed and what was measured.<br>3. Note the units and conditions — they determine whether a result is significant.<br>4. If the passage describes multiple trials, the repeated measurement is almost always the dependent variable.<br><br>A method question is rarely a fact recall — it is a careful reading of what the experiment actually did.`}
        ]
      },
    ]
  };
})();